name: Generate Datas
on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:
jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - name: Checkout Repository
        uses: actions/checkout@v2


      - name: Create output directory
        run: mkdir -p dist


      - name: Generate Snake Animation
        uses: Platane/snk@v2.0.0
  
        with:
          github_user_name: sameer3841
          svg_out_path: dist/github-contribution-grid-snake.svg
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Upload the Snake SVG
        uses: actions/upload-artifact@v2
        with:
          name: snake-contribution-grid
          path: dist/github-contribution-grid-snake.svg
